run:
  timeout: 5m

issues:
  exclude-dirs:
    - node_modules
    - vendor
    - coverage

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
